version: '3.8'

services:
  web:
    image: cadastrodebeneficios-web:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web-swarm"
        - "traefik.http.routers.cadastro-web.rule=Host(`cadastro.helthcorp.com.br`)"
        - "traefik.http.routers.cadastro-web.entrypoints=websecure"
        - "traefik.http.routers.cadastro-web.tls=true"
        - "traefik.http.routers.cadastro-web.tls.certresolver=lets-encrypt"
        - "traefik.http.services.cadastro-web.loadbalancer.server.port=80"
        - "traefik.http.middlewares.cadastro-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.cadastro-redirect.redirectscheme.permanent=true"
        - "traefik.http.routers.cadastro-http.rule=Host(`cadastro.helthcorp.com.br`)"
        - "traefik.http.routers.cadastro-http.entrypoints=web"
        - "traefik.http.routers.cadastro-http.middlewares=cadastro-redirect"
    networks:
      - cadastro-beneficios-network
      - web-swarm

networks:
  cadastro-beneficios-network:
    external: true
    name: cadastro_cadastro-beneficios-network
  web-swarm:
    external: true
