// Mocks generated by Mockito 5.4.4 from annotations
// in cadastro_beneficios/test/domain/usecases/auth/get_current_user_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cadastro_beneficios/core/errors/failures.dart' as _i5;
import 'package:cadastro_beneficios/domain/entities/auth_token.dart' as _i6;
import 'package:cadastro_beneficios/domain/entities/user.dart' as _i7;
import 'package:cadastro_beneficios/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>> loginWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithEmail,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>>.value(
            _FakeEither_0<_i5.Failure, _i6.AuthToken>(
          this,
          Invocation.method(
            #loginWithEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>> loginWithGoogle(
          {required String? idToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithGoogle,
          [],
          {#idToken: idToken},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>>.value(
            _FakeEither_0<_i5.Failure, _i6.AuthToken>(
          this,
          Invocation.method(
            #loginWithGoogle,
            [],
            {#idToken: idToken},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>> register({
    required String? name,
    required String? email,
    required String? password,
    required String? phoneNumber,
    String? cpf,
    String? birthDate,
    String? cep,
    String? logradouro,
    String? numero,
    String? complemento,
    String? bairro,
    String? cidade,
    String? estado,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #name: name,
            #email: email,
            #password: password,
            #phoneNumber: phoneNumber,
            #cpf: cpf,
            #birthDate: birthDate,
            #cep: cep,
            #logradouro: logradouro,
            #numero: numero,
            #complemento: complemento,
            #bairro: bairro,
            #cidade: cidade,
            #estado: estado,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>>.value(
            _FakeEither_0<_i5.Failure, _i6.AuthToken>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #name: name,
              #email: email,
              #password: password,
              #phoneNumber: phoneNumber,
              #cpf: cpf,
              #birthDate: birthDate,
              #cep: cep,
              #logradouro: logradouro,
              #numero: numero,
              #complemento: complemento,
              #bairro: bairro,
              #cidade: cidade,
              #estado: estado,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> forgotPassword(
          {required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [],
          {#email: email},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #forgotPassword,
            [],
            {#email: email},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {
            #token: token,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {
              #token: token,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>> refreshToken(
          {required String? refreshToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
          {#refreshToken: refreshToken},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>>.value(
            _FakeEither_0<_i5.Failure, _i6.AuthToken>(
          this,
          Invocation.method(
            #refreshToken,
            [],
            {#refreshToken: refreshToken},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthToken>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.User>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.User>>.value(
            _FakeEither_0<_i5.Failure, _i7.User>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isAuthenticated() =>
      (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isAuthenticated,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> sendVerificationCode({
    required String? phoneNumber,
    required _i3.VerificationMethod? method,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendVerificationCode,
          [],
          {
            #phoneNumber: phoneNumber,
            #method: method,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #sendVerificationCode,
            [],
            {
              #phoneNumber: phoneNumber,
              #method: method,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> verifyCode({
    required String? phoneNumber,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyCode,
          [],
          {
            #phoneNumber: phoneNumber,
            #code: code,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #verifyCode,
            [],
            {
              #phoneNumber: phoneNumber,
              #code: code,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.User>> completeProfile({
    required String? cpf,
    required String? phoneNumber,
    required String? cep,
    required String? street,
    required String? number,
    String? complement,
    required String? neighborhood,
    required String? city,
    required String? state,
    String? birthDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeProfile,
          [],
          {
            #cpf: cpf,
            #phoneNumber: phoneNumber,
            #cep: cep,
            #street: street,
            #number: number,
            #complement: complement,
            #neighborhood: neighborhood,
            #city: city,
            #state: state,
            #birthDate: birthDate,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.User>>.value(
            _FakeEither_0<_i5.Failure, _i7.User>(
          this,
          Invocation.method(
            #completeProfile,
            [],
            {
              #cpf: cpf,
              #phoneNumber: phoneNumber,
              #cep: cep,
              #street: street,
              #number: number,
              #complement: complement,
              #neighborhood: neighborhood,
              #city: city,
              #state: state,
              #birthDate: birthDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.User>>);
}
