// Mocks generated by Mockito 5.4.4 from annotations
// in cadastro_beneficios/test/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cadastro_beneficios/core/services/google_auth_service.dart'
    as _i10;
import 'package:cadastro_beneficios/core/services/token_service.dart' as _i8;
import 'package:cadastro_beneficios/data/datasources/auth_local_datasource.dart'
    as _i7;
import 'package:cadastro_beneficios/data/datasources/auth_remote_datasource.dart'
    as _i4;
import 'package:cadastro_beneficios/data/models/auth_token_model.dart' as _i2;
import 'package:cadastro_beneficios/data/models/user_model.dart' as _i3;
import 'package:cadastro_beneficios/domain/entities/auth_token.dart' as _i9;
import 'package:cadastro_beneficios/domain/repositories/auth_repository.dart'
    as _i6;
import 'package:google_sign_in/google_sign_in.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthTokenModel_0 extends _i1.SmartFake
    implements _i2.AuthTokenModel {
  _FakeAuthTokenModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i4.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthTokenModel> loginWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithEmail,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i2.AuthTokenModel>.value(_FakeAuthTokenModel_0(
          this,
          Invocation.method(
            #loginWithEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i2.AuthTokenModel>);

  @override
  _i5.Future<_i2.AuthTokenModel> loginWithGoogle({required String? idToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithGoogle,
          [],
          {#idToken: idToken},
        ),
        returnValue: _i5.Future<_i2.AuthTokenModel>.value(_FakeAuthTokenModel_0(
          this,
          Invocation.method(
            #loginWithGoogle,
            [],
            {#idToken: idToken},
          ),
        )),
      ) as _i5.Future<_i2.AuthTokenModel>);

  @override
  _i5.Future<_i2.AuthTokenModel> register({
    required String? name,
    required String? email,
    required String? password,
    required String? phoneNumber,
    String? cpf,
    String? birthDate,
    String? cep,
    String? logradouro,
    String? numero,
    String? complemento,
    String? bairro,
    String? cidade,
    String? estado,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #name: name,
            #email: email,
            #password: password,
            #phoneNumber: phoneNumber,
            #cpf: cpf,
            #birthDate: birthDate,
            #cep: cep,
            #logradouro: logradouro,
            #numero: numero,
            #complemento: complemento,
            #bairro: bairro,
            #cidade: cidade,
            #estado: estado,
          },
        ),
        returnValue: _i5.Future<_i2.AuthTokenModel>.value(_FakeAuthTokenModel_0(
          this,
          Invocation.method(
            #register,
            [],
            {
              #name: name,
              #email: email,
              #password: password,
              #phoneNumber: phoneNumber,
              #cpf: cpf,
              #birthDate: birthDate,
              #cep: cep,
              #logradouro: logradouro,
              #numero: numero,
              #complemento: complemento,
              #bairro: bairro,
              #cidade: cidade,
              #estado: estado,
            },
          ),
        )),
      ) as _i5.Future<_i2.AuthTokenModel>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> forgotPassword({required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [],
          {#email: email},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {
            #token: token,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthTokenModel> refreshToken(
          {required String? refreshToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
          {#refreshToken: refreshToken},
        ),
        returnValue: _i5.Future<_i2.AuthTokenModel>.value(_FakeAuthTokenModel_0(
          this,
          Invocation.method(
            #refreshToken,
            [],
            {#refreshToken: refreshToken},
          ),
        )),
      ) as _i5.Future<_i2.AuthTokenModel>);

  @override
  _i5.Future<_i3.UserModel> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i3.UserModel>.value(_FakeUserModel_1(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i5.Future<_i3.UserModel>);

  @override
  _i5.Future<void> sendVerificationCode({
    required String? phoneNumber,
    required _i6.VerificationMethod? method,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendVerificationCode,
          [],
          {
            #phoneNumber: phoneNumber,
            #method: method,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> verifyCode({
    required String? phoneNumber,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyCode,
          [],
          {
            #phoneNumber: phoneNumber,
            #code: code,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserModel> completeProfile({
    required String? cpf,
    required String? phoneNumber,
    required String? cep,
    required String? street,
    required String? number,
    String? complement,
    required String? neighborhood,
    required String? city,
    required String? state,
    String? birthDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeProfile,
          [],
          {
            #cpf: cpf,
            #phoneNumber: phoneNumber,
            #cep: cep,
            #street: street,
            #number: number,
            #complement: complement,
            #neighborhood: neighborhood,
            #city: city,
            #state: state,
            #birthDate: birthDate,
          },
        ),
        returnValue: _i5.Future<_i3.UserModel>.value(_FakeUserModel_1(
          this,
          Invocation.method(
            #completeProfile,
            [],
            {
              #cpf: cpf,
              #phoneNumber: phoneNumber,
              #cep: cep,
              #street: street,
              #number: number,
              #complement: complement,
              #neighborhood: neighborhood,
              #city: city,
              #state: state,
              #birthDate: birthDate,
            },
          ),
        )),
      ) as _i5.Future<_i3.UserModel>);

  @override
  _i5.Future<void> sendVerificationCodeV2(String? type) => (super.noSuchMethod(
        Invocation.method(
          #sendVerificationCodeV2,
          [type],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> verifyCodeV2(
    String? type,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyCodeV2,
          [
            type,
            code,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, bool>> getVerificationStatus() => (super.noSuchMethod(
        Invocation.method(
          #getVerificationStatus,
          [],
        ),
        returnValue: _i5.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i5.Future<Map<String, bool>>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i7.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> cacheUser(_i3.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #cacheUser,
          [user],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserModel?> getCachedUser() => (super.noSuchMethod(
        Invocation.method(
          #getCachedUser,
          [],
        ),
        returnValue: _i5.Future<_i3.UserModel?>.value(),
      ) as _i5.Future<_i3.UserModel?>);

  @override
  _i5.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [TokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenService extends _i1.Mock implements _i8.TokenService {
  MockTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveToken(_i9.AuthToken? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i9.AuthToken?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i5.Future<_i9.AuthToken?>.value(),
      ) as _i5.Future<_i9.AuthToken?>);

  @override
  _i5.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> hasToken() => (super.noSuchMethod(
        Invocation.method(
          #hasToken,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GoogleAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthService extends _i1.Mock implements _i10.GoogleAuthService {
  MockGoogleAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> signIn() => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #signIn,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isSignedIn() => (super.noSuchMethod(
        Invocation.method(
          #isSignedIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i12.GoogleSignInAccount?> getCurrentAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentAccount,
          [],
        ),
        returnValue: _i5.Future<_i12.GoogleSignInAccount?>.value(),
      ) as _i5.Future<_i12.GoogleSignInAccount?>);

  @override
  _i5.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
